// add_missing.mjs - Add missing state vars and replace payment buttons
import fs from 'fs';
let c = fs.readFileSync('src/components/landing/BookingWizardClient.tsx', 'utf8');
let changes = 0;
function R(oldStr, newStr, name) { if (c.includes(oldStr)) { c = c.replace(oldStr, newStr); changes++; console.log('OK:', name); } else { console.log('NF:', name); } }
const NL = '\r\n';
// 1. Icons
R(' Users, Calendar, Layers, Sparkles, Shield, Plus, Minus, X, ExternalLink, Zap, Eye, Server,' + NL + '} from "lucide-react";', ' Users, Calendar, Layers, Sparkles, Shield, Plus, Minus, X, ExternalLink, Zap, Eye, Server,' + NL + ' Search, AlertCircle,' + NL + '} from "lucide-react";', 'Icons');
// 2. State vars before selectedFeatures
const SI = NL + ' // Domain search state' + NL + ' const [selectedDomains, setSelectedDomains] = useState<SelectedDomain[]>([]);' + NL + ' const [domainSearchResults, setDomainSearchResults] = useState<DomainSearchResult[]>([]);' + NL + ' const [domainSearching, setDomainSearching] = useState(false);' + NL + ' const [domainHasSearched, setDomainHasSearched] = useState(false);' + NL + ' const [domainError, setDomainError] = useState("");' + NL + ' const [selectedTld, setSelectedTld] = useState(".com");' + NL + ' // Payment QR state' + NL + ' const [paymentQrUrls, setPaymentQrUrls] = useState<{bank?: string; momo?: string}>({});' + NL + ' const [selectedPayment, setSelectedPayment] = useState<string>("");' + NL + ' // Computed domain total' + NL + ' const selectedDomainTotal = selectedDomains.reduce((s, d) => s + d.price, 0);' + NL + ' // Toggle domain selection' + NL + ' function toggleDomain(domain: string, price: number) {' + NL + ' setSelectedDomains(prev => {' + NL + ' const exists = prev.find(d => d.domain === domain);' + NL + ' if (exists) return prev.filter(d => d.domain !== domain);' + NL + ' return [...prev, { domain, price }];' + NL + ' });' + NL + ' }' + NL + ' // Search domain function' + NL + ' async function searchDomain() {' + NL + ' if (domainName.trim().length < 2 || !domainName.includes(".")) return;' + NL + ' setDomainSearching(true);' + NL + ' setDomainError("");' + NL + ' try {' + NL + ' const tld = selectedTld.replace(/^\\./, "");' + NL + ' const res = await fetch("/api/pricing/domain-search?keyword=" + encodeURIComponent(domainName) + "&tld=" + tld);' + NL + ' const json = await res.json();' + NL + ' const results = json.data ?? [];' + NL + ' setDomainSearchResults(results);' + NL + ' setDomainHasSearched(true);' + NL + ' const autoSelected = results' + NL + ' .filter(r => r.available && (r.price ?? 0) > 0)' + NL + ' .map(r => ({ domain: r.domain, price: r.price ?? 0 }));' + NL + ' setSelectedDomains(autoSelected);' + NL + ' } catch {' + NL + ' setDomainError("Khong the kiem tra domain. Vui long thu lai.");' + NL + ' } finally {' + NL + ' setDomainSearching(false);' + NL + ' }' + NL + ' }' + NL + ' // Load payment QR URLs' + NL + ' useEffect(() => {' + NL + ' fetch("/api/v1/payment-methods")' + NL + ' .then(r => r.json())' + NL + ' .then(json => {' + NL + ' const d = json.data ?? {};' + NL + ' setPaymentQrUrls({ bank: d.bank?.qrUrl ?? null, momo: d.momo?.qrUrl ?? null });' + NL + ' })' + NL + ' .catch(() => {});' + NL + ' }, []);' + NL;
R('const [selectedFeatures, setSelectedFeatures] = useState<string[]>([]);', SI + 'const [selectedFeatures, setSelectedFeatures] = useState<string[]>([]);', 'State vars');
// 3. Remove startDate
R('const [startDate, setStartDate] = useState("");' + NL, '', 'startDate removal');
// 4. Remove duration
R('const [duration, setDuration] = useState("");' + NL, '', 'duration removal');
// 5. Notes
R('notes: `Dịch vụ: ${svc?.title ?? ""} | Tính năng: ${selectedFeatures.length} | Ghi chú đội ngũ: ${talentNote || "—"} | Bắt đầu: ${startDate || "—"} | Thời gian: ${duration || "—"}`,', 'notes: `Dịch vụ: ${svc?.title ?? ""} | Tính năng: ${selectedFeatures.length} | Ghi chú đội ngũ: ${talentNote || "—"}`,', 'Notes');
// 6. domainTotal
R('const domainTotal = domainPurchaseNow && domainName' + NL + ' ? (domainPrices.find(d => domainName.endsWith(d.extension))?.registrationPrice ?? 0) : 0;', 'const domainTotal = domainPurchaseNow ? selectedDomainTotal : 0;', 'domainTotal');
// 7. Payment buttons
const oldPay = '{/* Payment method */}' + NL + ' <div className="mb-4">' + NL + ' <label style={{ color: DS.text3, fontSize: 11, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>Hình thức chuyển khoản</label>' + NL + ' <div className="flex gap-3 flex-wrap">' + NL + ' {[{ id: "bank", label: t("bankTransfer"), icon: "🏦" }, { id: "vnpay", label: "VNPay QR", icon: "📱" }, { id: "momo", label: "Momo", icon: "💜" }].map(m => (' + NL + ' <button key={m.id} style={{ padding: "10px 18px", borderRadius: 10, fontSize: 13, cursor: "pointer", background: "rgba(15,23,42,0.5)", border: `1px solid ${DS.border}`, color: DS.text3, display: "flex", alignItems: "center", gap: 8, fontFamily: DS.mono }}>' + NL + ' <span style={{ fontSize: 16 }}>{m.icon}</span>{m.label}' + NL + ' </button>' + NL + ' ))}' + NL + ' </div>' + NL + ' </div>';
const newPay = '{/* Payment method */}' + NL + ' <div className="mb-4">' + NL + ' <label style={{ color: DS.text3, fontSize: 11, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>Hình thức thanh toán</label>' + NL + ' <div className="flex gap-3 flex-wrap">' + NL + ' {[{ id: "bank", label: t("bankTransfer"), icon: "🏦" }, { id: "momo", label: "MoMo", icon: "💜" }].map(m => {' + NL + ' const isSel = selectedPayment === m.id;' + NL + ' return (' + NL + ' <motion.button key={m.id}' + NL + ' onClick={() => setSelectedPayment(isSel ? "" : m.id)}' + NL + ' whileHover={{ scale: 1.02 }}' + NL + ' style={{ padding: "10px 18px", borderRadius: 10, fontSize: 13, cursor: "pointer",' + NL + ' background: isSel ? `${DS.blue}15` : "rgba(15,23,42,0.5)",' + NL + ' border: isSel ? `1.5px solid ${DS.blue}` : `1px solid ${DS.border}`,' + NL + ' color: isSel ? DS.blue : DS.text3, display: "flex", alignItems: "center", gap: 8, fontFamily: DS.mono }}>' + NL + ' <span style={{ fontSize: 16 }}>{m.icon}</span>{m.label}' + NL + ' {isSel && <Check size={11} style={{ color: DS.blue, marginLeft: 4 }} />}' + NL + ' </motion.button>' + NL + ' );' + NL + ' })}' + NL + ' </div>' + NL + ' </div>' + NL + ' {/* QR Code display */}' + NL + ' {selectedPayment && paymentQrUrls[selectedPayment] && (' + NL + ' <div className="mt-4 p-4 rounded-xl text-center" style={{ background: "rgba(15,23,42,0.5)", border: `1px solid ${DS.blue}30` }}>' + NL + ' <div style={{ color: DS.blue, fontSize: 11, fontFamily: DS.mono, letterSpacing: "0.1em", marginBottom: 8 }}>QUÉT MÃ QR ĐỂ THANH TOÁN</div>' + NL + ' <img src={paymentQrUrls[selectedPayment]} alt="QR Code" style={{ maxWidth: 200, maxHeight: 200, margin: "0 auto", borderRadius: 12 }} />' + NL + ' <div style={{ color: DS.text4, fontSize: 11, marginTop: 8 }}>Quét mã QR bằng app {selectedPayment === "bank" ? "Ngân hàng" : "MoMo"} để thanh toán</div>' + NL + ' </div>' + NL + ' )}';
R(oldPay, newPay, 'Payment buttons');
fs.writeFileSync('src/components/landing/BookingWizardClient.tsx', c);
console.log(`\nDone! Applied ${changes} changes. Lines: ${c.split('\n').length}`);
