import fs from 'fs';
const c = fs.readFileSync('src/components/landing/BookingWizardClient.tsx', 'utf8');
let c2 = c;
let changes = 0;
function R(a, b, n) { if (c2.includes(a)) { c2 = c2.replace(a, b); changes++; console.log('OK:', n); } else { console.log('NF:', n); } }
// Icons
R(' Users, Calendar, Layers, Sparkles, Shield, Plus, Minus, X, ExternalLink, Zap, Eye, Server,\r\n} from "lucide-react";', ' Users, Calendar, Layers, Sparkles, Shield, Plus, Minus, X, ExternalLink, Zap, Eye, Server,\r\n Search, AlertCircle,\r\n} from "lucide-react";', 'Icons');
// State vars
const si = '\r\n const [selectedFeatures, setSelectedFeatures] = useState<string[]>([]);';
const newsi = '\r\n // Domain search state\r\n const [selectedDomains, setSelectedDomains] = useState<SelectedDomain[]>([]);\r\n const [domainSearchResults, setDomainSearchResults] = useState<DomainSearchResult[]>([]);\r\n const [domainSearching, setDomainSearching] = useState(false);\r\n const [domainHasSearched, setDomainHasSearched] = useState(false);\r\n const [domainError, setDomainError] = useState("");\r\n const [selectedTld, setSelectedTld] = useState(".com");\r\n // Payment QR state\r\n const [paymentQrUrls, setPaymentQrUrls] = useState<{bank?: string; momo?: string}>({});\r\n const [selectedPayment, setSelectedPayment] = useState<string>("");\r\n // Computed domain total\r\n const selectedDomainTotal = selectedDomains.reduce((s, d) => s + d.price, 0);\r\n // Toggle domain selection\r\n function toggleDomain(domain: string, price: number) {\r\n setSelectedDomains(prev => {\r\n const exists = prev.find(d => d.domain === domain);\r\n if (exists) return prev.filter(d => d.domain !== domain);\r\n return [...prev, { domain, price }];\r\n });\r\n }\r\n // Search domain function\r\n async function searchDomain() {\r\n if (domainName.trim().length < 2 || !domainName.includes(".")) return;\r\n setDomainSearching(true);\r\n setDomainError("");\r\n try {\r\n const tld = selectedTld.replace(/^\\./, "");\r\n const res = await fetch("/api/pricing/domain-search?keyword=" + encodeURIComponent(domainName) + "&tld=" + tld);\r\n const json = await res.json();\r\n const results = json.data ?? [];\r\n setDomainSearchResults(results);\r\n setDomainHasSearched(true);\r\n const autoSelected = results\r\n .filter(r => r.available && (r.price ?? 0) > 0)\r\n .map(r => ({ domain: r.domain, price: r.price ?? 0 }));\r\n setSelectedDomains(autoSelected);\r\n } catch {\r\n setDomainError("Khong the kiem tra domain. Vui long thu lai.");\r\n } finally {\r\n setDomainSearching(false);\r\n }\r\n }\r\n // Load payment QR URLs\r\n useEffect(() => {\r\n fetch("/api/v1/payment-methods")\r\n .then(r => r.json())\r\n .then(json => {\r\n const d = json.data ?? {};\r\n setPaymentQrUrls({ bank: d.bank?.qrUrl ?? null, momo: d.momo?.qrUrl ?? null });\r\n })\r\n .catch(() => {});\r\n }, []);\r\n const [selectedFeatures, setSelectedFeatures] = useState<string[]>([]);';
R(si, newsi, 'State vars');
// startDate
R('const [startDate, setStartDate] = useState("");\r\n', '', 'startDate');
// duration
R('const [duration, setDuration] = useState("");\r\n', '', 'duration');
// notes
R('notes: `Dịch vụ: ${svc?.title ?? ""} | Tính năng: ${selectedFeatures.length} | Ghi chú đội ngũ: ${talentNote || "—"} | Bắt đầu: ${startDate || "—"} | Thời gian: ${duration || "—"}`,',
'notes: `Dịch vụ: ${svc?.title ?? ""} | Tính năng: ${selectedFeatures.length} | Ghi chú đội ngũ: ${talentNote || "—"}`,', 'Notes');
// domainTotal
R('const domainTotal = domainPurchaseNow && domainName\r\n ? (domainPrices.find(d => domainName.endsWith(d.extension))?.registrationPrice ?? 0) : 0;',
'const domainTotal = domainPurchaseNow ? selectedDomainTotal : 0;', 'domainTotal');
// Payment buttons
const oldpay = '{/* Payment method */}\r\n <div className="mb-4">\r\n <label style={{ color: DS.text3, fontSize: 11, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>Hình thức chuyển khoản</label>\r\n  <div className="flex gap-3 flex-wrap">\r\n {[{ id: "bank", label: t("bankTransfer"), icon: "🏦" }, { id: "vnpay", label: "VNPay QR", icon: "📱" }, { id: "momo", label: "Momo", icon: "💜" }].map(m => (\r\n <button key={m.id} style={{ padding: "10px 18px", borderRadius: 10, fontSize: 13, cursor: "pointer", background: "rgba(15,23,42,0.5)", border: `1px solid ${DS.border}`, color: DS.text3, display: "flex", alignItems: "center", gap: 8, fontFamily: DS.mono }}>\r\n <span style={{ fontSize: 16 }}>{m.icon}</span>{m.label}\r\n </button>\r\n ))}\r\n </div></div>';
const newpay = '{/* Payment method */}\r\n <div className="mb-4">\r\n <label style={{ color: DS.text3, fontSize: 11, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>Hình thức thanh toán</label>\r\n <div className="flex gap-3 flex-wrap">\r\n {[{ id: "bank", label: t("bankTransfer"), icon: "🏦" }, { id: "momo", label: "MoMo", icon: "💜" }].map(m => {\r\n const isSel = selectedPayment === m.id;\r\n return (\r\n <motion.button key={m.id}\r\n onClick={() => setSelectedPayment(isSel ? "" : m.id)}\r\n whileHover={{ scale: 1.02 }}\r\n style={{ padding: "10px 18px", borderRadius: 10, fontSize: 13, cursor: "pointer",\r\n background: isSel ? `${DS.blue}15` : "rgba(15,23,42,0.5)",\r\n border: isSel ? `1.5px solid ${DS.blue}` : `1px solid ${DS.border}`,\r\n color: isSel ? DS.blue : DS.text3, display: "flex", alignItems: "center", gap: 8, fontFamily: DS.mono }}>\r\n <span style={{ fontSize: 16 }}>{m.icon}</span>{m.label}\r\n {isSel && <Check size={11} style={{ color: DS.blue, marginLeft: 4 }} />}\r\n </motion.button>\r\n );\r\n })}\r\n </div>\r\n  </div>\r\n {selectedPayment && paymentQrUrls[selectedPayment] && (\r\n <div className="mt-4 p-4 rounded-xl text-center" style={{ background: "rgba(15,23,42,0.5)", border: `1px solid ${DS.blue}30` }}>\r\n <div style={{ color: DS.blue, fontSize: 11, fontFamily: DS.mono, letterSpacing: "0.1em", marginBottom: 8 }}>QUÉT MÃ QR ĐỂ THANH TOÁN</div>\r\n <img src={paymentQrUrls[selectedPayment]} alt="QR Code" style={{ maxWidth: 200, maxHeight: 200, margin: "0 auto", borderRadius: 12 }} />\r\n  <div style={{ color: DS.text4, fontSize: 11, marginTop: 8 }}>Quét mã QR bằng app {selectedPayment === "bank" ? "Ngân hàng" : "MoMo"} để thanh toán</div>\r\n </div>\r\n )}';
R(oldpay, newpay, 'Payment buttons');
fs.writeFileSync('src/components/landing/BookingWizardClient.tsx', c2);
console.log(`\nDone! ${changes} changes. Lines: ${c2.split('\n').length}`);
