// Generate the debounce block with correct indentation
const lines = [
 ' const emailTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);',
 '',
 ' useEffect(() => {',
 ' let cancelled = false;',
 ' if (emailTimeout.current) clearTimeout(emailTimeout.current);',
 ' emailTimeout.current = setTimeout(() => {',
 ' fetch(`/api/pricing/config?lang=${locale}${email ? `&email=${encodeURIComponent(email)}` : ""}`)',
 ' .then(r => r.json())',
 ' .then(json => {',
 ' if (cancelled || !json?.data) return;',
 ' const cfg: PricingConfig = json.data;',
 '',
 ' // ── Packages: chỉ lấy type="web" (loại bỏ app/dashboard/SEO) ──',
 ' if (cfg.packages?.length) {',
 ' const webPkgs = cfg.packages.filter((p: WizardPackage) =>',
 ' !p.type || p.type === "web" || p.type === "custom_web"',
 ' );',
 ' const withPopular = webPkgs.map((p: WizardPackage) => ({',
 ' ...p,',
 ' popular: p.popular ?? (p.slug === "business"),',
 ' }));',
 ' if (withPopular.length > 0) setPackages(withPopular);',
 ' }',
 '',
 ' // ── Features: nhóm theo category ──',
 ' if (cfg.features?.length) {',
 ' const grouped: Record<string, WizardFeature[]> = {};',
 ' for (const f of cfg.features) {',
 ' const cat = f.category || "Nâng cao";',
 ' if (!grouped[cat]) grouped[cat] = [];',
 ' grouped[cat]!.push(f);',
 ' }',
 ' if (Object.keys(grouped).length) setFeatureOptions(grouped);',
 ' }',
 '',
 ' // ── Addons ──',
 ' if (cfg.addons?.length) setExtraOptions(cfg.addons);',
 '',
 ' // ── Hosting + Domain ──',
 ' if (cfg.hostingPlans?.length) setHostingPlans(cfg.hostingPlans);',
 ' if (cfg.domainPrices?.length) setDomainPrices(cfg.domainPrices);',
 '',
 ' // ── Rates ──',
 ' if (cfg.lpRate) setLpRate(cfg.lpRate);',
 ' if (cfg.vatRate !== undefined) setVatRate(cfg.vatRate);',
 '',
 ' // ── Customer LP balance (if email provided) ──',
 ' if (email && cfg.customerLp) {',
 ' setLpBalance(cfg.customerLp.balance ?? 0);',
  ' }',
 ' })',
 ' .catch(() => { /* keep fallback */ });',
 ' return () => { cancelled = true; };',
 ' }, 500);',
 ' });',
 ' }, [locale, email]);',
];

console.log(lines.join('\n'));
