// phase2_domain.mjs — Replace domain input UI using byte-index replacement
import fs from 'fs';
const c0 = fs.readFileSync('src/components/landing/BookingWizardClient.tsx', 'utf8');
let c = c0;

// Build the new domain input section line by line
const BT = String.fromCharCode(96); // backtick
const DS = new Proxy({}, { get: (_, k) => `\${${k}}` }); // e.g. DS.blue → "${DS.blue}"

// Build the new domain input section
const newLines = [
 `<div className="mb-6">`,
 ` <label style={{ color: DS.text3, fontSize: 12, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>TÊN MIỀN BẠN MUỐN ĐĂNG KÝ</label>`,
 ` <div className="flex gap-3">`,
 ` <input`,
 ` value={domainName}`,
 ` onChange={e => setDomainName(e.target.value)}`,
 ` placeholder="ví dụ: mysite.com"`,
 ` style={{ flex: 1, background: "rgba(15,23,42,0.6)", border: ${BT}1px solid ${DS.border}${BT}, borderRadius: 10, padding: "12px 16px", color: DS.text, fontSize: 15, outline: "none", fontFamily: DS.body, boxSizing: "border-box" }}`,
 ` />`,
 ` {domainPrices.length > 0 && (`,
 ` <select`,
 ` value={selectedTld}`,
 ` onChange={e => { setSelectedTld(e.target.value); setDomainHasSearched(false); setDomainSearchResults([]); }}`,
 ` style={{ background: "rgba(15,23,42,0.8)", border: ${BT}1px solid ${DS.border}${BT}, borderRadius: 10, padding: "12px 14px", color: DS.text, fontSize: 14, fontFamily: DS.mono, outline: "none", cursor: "pointer" }}>`,
 ` {domainPrices.map(d => <option key={d.extension} value={d.extension} style={{ background: "#0F172A" }}>{d.extension}</option>)}`,
 ` </select>`,
 ` )}`,
 ` </div>`,
 ``,
 ` {/* Search button */}`,
 ` <div className="flex gap-2 mt-3">`,
 ` <motion.button`,
 ` onClick={searchDomain}`,
 ` disabled={domainSearching || domainName.trim().length < 2}`,
 ` className="flex items-center gap-2 rounded-xl px-5 py-3 font-semibold transition-all disabled:cursor-not-allowed"`,
 ` style={{ background: domainSearching ? "rgba(59,130,246,0.1)" : "rgba(59,130,246,0.15)", border: ${BT}1px solid ${DS.blue}50${BT}, color: DS.blue, cursor: domainSearching ? "not-allowed" : "pointer" }}`,
 ` whileHover={domainSearching ? {} : { scale: 1.02 }}>`,
 ` {domainSearching ? (`,
 ` <><div className="w-4 h-4 animate-spin rounded-full border-2 border-blue-400 border-t-transparent" /><span>Kiểm tra...</span></>`,
 ` ) : (`,
 ` <><Search size={16} /><span style={{ fontFamily: DS.mono, fontSize: 13 }}>Kiểm tra</span></>`,
 ` )}`,
 ` </motion.button>`,
 ` </div>`,
 ``,
 ` {domainError && (`,
 ` <div className="mt-2 flex items-center gap-2">`,
 ` <AlertCircle size={13} style={{ color: DS.red }} />`,
 ` <span style={{ color: DS.red, fontSize: 12 }}>{domainError}</span>`,
 ` </div>`,
 ` )}`,
 ``,
 ` {/* Domain search results */}`,
 ` {domainHasSearched && (`,
 ` <div className="mt-4 space-y-3">`,
 ` {domainSearchResults.length === 0 && (`,
 ` <div className="p-4 rounded-xl text-center" style={{ background: "rgba(15,23,42,0.4)", border: ${BT}1px solid ${DS.border}${BT} }}>`,
 ` <span style={{ color: DS.text4, fontSize: 13 }}>Không tìm thấy kết quả</span>`,
 ` </div>`,
 ` )}`,
 ` {domainSearchResults.length > 0 && (`,
 ` <div>`,
 ``,
 ` {/* Primary domain */}`,
 ` {(() => {`,
 ` const primary = domainSearchResults[0];`,
 ` if (!primary) return null;`,
 ` const isSel = selectedDomains.some(d => d.domain === primary.domain);`,
 ` const avail = primary.available && (primary.price ?? 0) > 0;`,
 ` return (`,
 ` <div className="mb-3">`,
 ` {avail ? (`,
 ` <div>`,
 ` <div style={{ color: DS.text4, fontSize: 11, fontFamily: DS.mono, marginBottom: 6 }}>DOMAIN CHÍNH</div>`,
 ` <div className="flex items-center justify-between p-4 rounded-xl cursor-pointer"`,
 ` style={{ background: isSel ? ${BT}rgba(59,130,246,0.12)${BT} : ${BT}rgba(34,197,94,0.06)${BT}, border: isSel ? ${BT}1.5px solid ${DS.blue}${BT} : ${BT}1px solid ${DS.green}30${BT} }}`,
 ` onClick={() => { if(avail) toggleDomain(primary.domain, primary.price ?? 0); }}>`,
 ` <div className="flex items-center gap-3">`,
 ` <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ background: isSel ? ${BT}${DS.blue}25${BT} : ${BT}${DS.green}20${BT}, border: isSel ? ${BT}2px solid ${DS.blue}${BT} : ${BT}2px solid ${DS.green}${BT} }}>`,
 ` <Check size={12} style={{ color: isSel ? DS.blue : DS.green }} />`,
 ` </div>`,
 ` <span style={{ color: DS.text, fontSize: 14, fontFamily: DS.mono, fontWeight: 700 }}>{primary.domain}</span>`,
 ` </div>`,
 ` <div className="flex items-center gap-3">`,
 ` {isSel && <span style={{ color: DS.blue, fontSize: 11, fontFamily: DS.mono, background: ${BT}${DS.blue}15${BT}, padding: "2px 8px", borderRadius: 6 }}>Đã chọn</span>}`,
 ` {primary.price > 0 && <span style={{ color: DS.green, fontSize: 13, fontFamily: DS.mono, fontWeight: 700 }}>{fmtVND(primary.price)}</span>}`,
 ` </div>`,
 ` </div>`,
 ` </div>`,
 ` ) : (`,
 ` <div>`,
 ` <div style={{ color: DS.text4, fontSize: 11, fontFamily: DS.mono, marginBottom: 6 }}>DOMAIN CHÍNH</div>`,
 ` <div className="flex items-center justify-between p-4 rounded-xl"`,
 ` style={{ background: "rgba(255,255,255,0.03)", border: ${BT}1px solid ${DS.border}${BT}, opacity: 0.7 }}>`,
 ` <div className="flex items-center gap-3">`,
 ` <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ background: "rgba(255,255,255,0.06)" }}>`,
 ` <X size={12} style={{ color: DS.text4 }} />`,
 ` </div>`,
 ` <div>`,
 ` <span style={{ color: DS.text3, fontSize: 14, fontFamily: DS.mono, fontWeight: 600 }}>{primary.domain}</span>`,
 ` <span style={{ color: DS.red, fontSize: 11, marginLeft: 8 }}>(đã được đăng ký)</span>`,
 ` </div>`,
 ` </div>`,
 ` </div>`,
 ` </div>`,
 ` )}`,
 ` </div>`,
 ` );`,
 ` })()}`,
 ``,
 ` {/* Alternative TLDs */}`,
 ` {domainSearchResults.length > 1 && (`,
 ` <div className="mt-3">`,
 ` <div style={{ color: DS.text4, fontSize: 11, fontFamily: DS.mono, marginBottom: 8 }}>GỢI Ý KHÁC</div>`,
 ` <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))", gap: 8 }}>`,
 ` {domainSearchResults.slice(1).map(result => {`,
 ` const isSel = selectedDomains.some(d => d.domain === result.domain);`,
 ` const avail = result.available && (result.price ?? 0) > 0;`,
 ` return (`,
 ` <div key={result.domain}`,
 ` className="flex items-center justify-between p-3 rounded-xl cursor-pointer"`,
 ` style={{ background: isSel ? ${BT}rgba(59,130,246,0.12)${BT} : avail ? ${BT}rgba(34,197,94,0.06)${BT} : "rgba(255,255,255,0.03)", border: isSel ? ${BT}1.5px solid ${DS.blue}${BT} : avail ? ${BT}1px solid ${DS.green}30${BT} : ${BT}1px solid ${DS.border}${BT}, opacity: avail ? 1 : 0.6 }}`,
 ` onClick={() => { if(avail) toggleDomain(result.domain, result.price ?? 0); }}>`,
 ` <div className="flex items-center gap-2">`,
 ` <div className="w-4 h-4 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: isSel ? ${BT}${DS.blue}20${BT} : ${BT}${DS.green}15${BT} }}>`,
 ` {isSel ? <Check size={9} style={{ color: DS.blue }} /> : avail ? <Check size={9} style={{ color: DS.green }} /> : <X size={9} style={{ color: DS.text4 }} />}`,
 ` </div>`,
 ` <span style={{ color: avail ? DS.text : DS.text3, fontSize: 12, fontFamily: DS.mono }}>{result.domain}</span>`,
 ` </div>`,
 ` {avail && result.price > 0 && (`,
 ` <span style={{ color: DS.green, fontSize: 11, fontFamily: DS.mono, fontWeight: 600 }}>{fmtVND(result.price)}</span>`,
 ` )}`,
 ` </div>`,
 ` );`,
 ` })}`,
 ` </div>`,
 ` </div>`,
 ` )}`,
 ``,
 ` {/* Selected summary */}`,
 ` {selectedDomains.length > 0 && (`,
 ` <div className="mt-4 p-3 rounded-xl" style={{ background: ${BT}${DS.blue}08${BT}, border: ${BT}1px solid ${DS.blue}25${BT} }}>`,
 ` <div className="flex items-center justify-between">`,
 ` <div className="flex items-center gap-2">`,
 ` <Check size={13} style={{ color: DS.blue }} />`,
 ` <span style={{ color: DS.blue, fontSize: 12, fontFamily: DS.mono }}>Đã chọn {selectedDomains.length} domain</span>`,
 ` </div>`,
 ` <span style={{ color: DS.blue, fontSize: 13, fontFamily: DS.mono, fontWeight: 700 }}>{fmtVND(selectedDomainTotal)}</span>`,
 ` </div>`,
 ` <div className="mt-2 flex flex-wrap gap-2">`,
 ` {selectedDomains.map(d => (`,
 ` <span key={d.domain} className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs" style={{ background: ${BT}${DS.blue}15${BT}, color: DS.blue, fontFamily: DS.mono }}>`,
 ` {d.domain}`,
 ` <button onClick={() => toggleDomain(d.domain, d.price)} style={{ background: "none", border: "none", cursor: "pointer", padding: 0, color: DS.blue, display: "flex" }}>`,
 ` <X size={10} />`,
 ` </button>`,
 ` </span>`,
 ` ))}`,
 ` </div>`,
 ` </div>`,
 ` )}`,
 ` </div>`,
 ` )}`,
 ` </div>`,
 ` )}`,
 ` </div>`,
 ` )}`,
 ` </div>`,
].join('\n');

const newSection = newLines + '\n';

// Find section boundaries
const labelIdx = c.indexOf('<label style={{ color: DS.text3, fontSize: 12, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>TÊN MIỀN BẠN MUỐN ĐĂNG KÝ</label>');
if (labelIdx < 0) { console.error('Label not found'); process.exit(1); }
const mb6Idx = c.lastIndexOf('<div className="mb-6">', labelIdx);
const ptIdx = c.indexOf(' {/* Purchase timing */}', labelIdx);
const divIdx = c.lastIndexOf('</div>', ptIdx);
const endIdx = divIdx + 6;
console.log(`Section: bytes ${mb6Idx} - ${endIdx} (${endIdx - mb6Idx} chars)`);

// Replace
c = c.substring(0, mb6Idx) + newSection + c.substring(endIdx);
console.log('Domain input replaced. Lines:', c.split('\n').length);

fs.writeFileSync('src/components/landing/BookingWizardClient.tsx', c);
console.log('Written');
