#!/usr/bin/env node
import fs from 'fs';

const f='src/components/landing/BookingWizardClient.tsx';
let c=fs.readFileSync(f,'utf8');

// 14 spaces indent (matching the original mb-6 div level)
const I=' '; // 14 spaces
const I2=' '; // 16 spaces
const I3=' '; // 18 spaces

const nd=[
I+'<div className="mb-6">',
I2+'<label style={{ color: DS.text3, fontSize: 12, fontFamily: DS.mono, letterSpacing: "0.1em", display: "block", marginBottom: 8 }}>TÊN MIỀN BẠN MUỐN ĐĂNG KÝ</label>',
I2+'<div className="flex gap-3">',
I3+'<input value={domainName} onChange={e => setDomainName(e.target.value)} placeholder="ví dụ: mysite.com"',
I3+'style={{ flex: 1, background: "rgba(15,23,42,0.6)", border: `1px solid ${DS.border}`, borderRadius: 10, padding: "12px 16px", color: DS.text, fontSize: 15, outline: "none", fontFamily: DS.body, boxSizing: "border-box" }} />',
I3+'{domainPrices.length > 0 && (',
I3+' <select value={domainName.includes(".") ? "." + domainName.split(".").pop() || ".com" : ".com"}',
I3+' onChange={e => { const base = domainName.includes(".") ? domainName.split(".")[0] || domainName : domainName; setDomainName(base + e.target.value); setDomainHasSearched(false); setDomainSearchResults([]); }}',
I3+' style={{ background: "rgba(15,23,42,0.8)", border: `1px solid ${DS.border}`, borderRadius: 10, padding: "12px 14px", color: DS.text, fontSize: 14, fontFamily: DS.mono, outline: "none", cursor: "pointer" }}>',
I3+' {domainPrices.map(d => <option key={d.extension} value={d.extension} style={{ background: "#0F172A" }}>{d.extension}</option>)}',
I3+' </select>',
I3+' )}',
I2+'</div>',
I2+'',
I2+' {/* Search button */}',
I2+'<div className="flex gap-2 mt-3">',
I3+'<motion.button onClick={searchDomain}',
I3+' disabled={domainSearching || domainName.trim().length < 2}',
I3+' className="flex items-center gap-2 rounded-xl px-5 py-3 font-semibold transition-all disabled:cursor-not-allowed"',
I3+' style={{ background: domainSearching ? "rgba(59,130,246,0.1)" : "rgba(59,130,246,0.15)", border: `1px solid ${DS.blue}50`, color: DS.blue, cursor: domainSearching ? "not-allowed" : "pointer" }}',
I3+' whileHover={domainSearching ? {} : { scale: 1.02 }}>',
I3+' {domainSearching ? (',
I3+' <><div className="w-4 h-4 animate-spin rounded-full border-2 border-blue-400 border-t-transparent" /><span>Kiểm tra...</span></>',
I3+' ) : (',
I3+' <><Search size={16} /><span style={{ fontFamily: DS.mono, fontSize: 13 }}>Kiểm tra</span></>',
I3+' )}',
I3+' </motion.button>',
I2+'</div>',
I2+'',
I2+'{domainError && (',
I3+'<div className="mt-2 flex items-center gap-2">',
I3+' <AlertCircle size={13} style={{ color: DS.red }} />',
I3+' <span style={{ color: DS.red, fontSize: 12 }}>{domainError}</span>',
I3+'</div>',
I2+')}',
I2+'',
I2+' {/* Domain search results */}',
I2+'{domainHasSearched && (',
I2+' <div className="mt-4 space-y-3">',
I2+' {domainSearchResults.length === 0 && (',
I2+' <div className="p-4 rounded-xl text-center" style={{ background: "rgba(15,23,42,0.4)", border: `1px solid ${DS.border}` }}>',
I2+' <span style={{ color: DS.text4, fontSize: 13 }}>Không tìm thấy kết quả</span>',
I2+' </div>',
I2+' )}',
I2+' {domainSearchResults.length > 0 && (',
I2+' <div>',
I2+'',
I2+' {/* Primary domain */}',
I2+' {(() => {',
I2+' const primary = domainSearchResults[0];',
I2+' const isSelected = selectedDomains.some(d => d.domain === primary.domain);',
I2+' const isAvailable = primary.available;',
I2+' return (',
I2+' <div className="mb-3">',
I2+' {isAvailable ? (',
I2+' <div>',
I2+' <div style={{ color: DS.text4, fontSize: 11, fontFamily: DS.mono, marginBottom: 6 }}>DOMAIN CHÍNH</div>',
I2+' <div className="flex items-center justify-between p-4 rounded-xl cursor-pointer"',
I2+' style={{ background: isSelected ? `rgba(59,130,246,0.12)` : `rgba(34,197,94,0.06)`, border: isSelected ? `1.5px solid ${DS.blue}` : `1px solid ${DS.green}30` }}',
I2+' onClick={() => { if(primary.available) toggleDomain(primary.domain, primary.price ?? 0); }}>',
I2+' <div className="flex items-center gap-3">',
I2+' <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ background: isSelected ? `${DS.blue}25` : `${DS.green}20`, border: isSelected ? `2px solid ${DS.blue}` : `2px solid ${DS.green}` }}>',
I2+' {isSelected ? <Check size={12} style={{ color: DS.blue }} /> : <Check size={12} style={{ color: DS.green }} />}',
I2+' </div>',
I2+' <span style={{ color: DS.text, fontSize: 14, fontFamily: DS.mono, fontWeight: 700 }}>{primary.domain}</span>',
I2+' </div>',
I2+' <div className="flex items-center gap-3">',
I2+' {isSelected && <span style={{ color: DS.blue, fontSize: 11, fontFamily: DS.mono, background: `${DS.blue}15`, padding: "2px 8px", borderRadius: 6 }}>Đã chọn</span>}',
I2+' {primary.price > 0 && <span style={{ color: DS.green, fontSize: 13, fontFamily: DS.mono, fontWeight: 700 }}>{fmtVND(primary.price)}</span>}',
I2+' </div>',
I2+' </div>',
I2+' </div>',
I2+' ) : (',
I2+' <div>',
I2+' <div style={{ color: DS.text4, fontSize: 11, fontFamily: DS.mono, marginBottom: 6 }}>DOMAIN CHÍNH</div>',
I2+' <div className="flex items-center justify-between p-4 rounded-xl"',
I2+' style={{ background: "rgba(255,255,255,0.03)", border: `1px solid ${DS.border}`, opacity: 0.7 }}>',
I2+' <div className="flex items-center gap-3">',
I2+' <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ background: "rgba(255,255,255,0.06)" }}>',
I2+' <X size={12} style={{ color: DS.text4 }} />',
I2+' </div>',
I2+' <div>',
I2+' <span style={{ color: DS.text3, fontSize: 14, fontFamily: DS.mono, fontWeight: 600 }}>{primary.domain}</span>',
I2+' <span style={{ color: DS.red, fontSize: 11, marginLeft: 8 }}>(đã được đăng ký)</span>',
I2+' </div>',
I2+' </div>',
I2+' </div>',
I2+' </div>',
I2+' )}',
I2+' </div>',
I2+' );',
I2+' })()}',
I2+'',
I2+' {/* Alternative TLDs */}',
I2+' {domainSearchResults.length > 1 && (',
I2+' <div className="mt-3">',
I2+' <div style={{ color: DS.text4, fontSize: 11, fontFamily: DS.mono, marginBottom: 8 }}>GỢI Ý KHÁC</div>',
I2+' <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))", gap: 8 }}>',
I2+' {domainSearchResults.slice(1).map(result => {',
I2+' const isSelected = selectedDomains.some(d => d.domain === result.domain);',
I2+' const isAvailable = result.available;',
I2+' return (',
I2+' <div key={result.domain}',
I2+' className="flex items-center justify-between p-3 rounded-xl cursor-pointer"',
I2+' style={{ background: isSelected ? `rgba(59,130,246,0.12)` : isAvailable ? `rgba(34,197,94,0.06)` : "rgba(255,255,255,0.03)", border: isSelected ? `1.5px solid ${DS.blue}` : isAvailable ? `1px solid ${DS.green}30` : `1px solid ${DS.border}`, opacity: isAvailable ? 1 : 0.6 }}',
I2+' onClick={() => { if(result.available) toggleDomain(result.domain, result.price ?? 0); }}>',
I2+' <div className="flex items-center gap-2">',
I2+' <div className="w-4 h-4 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: isSelected ? `${DS.blue}20` : `${DS.green}15` }}>',
I2+' {isSelected ? <Check size={9} style={{ color: DS.blue }} /> : isAvailable ? <Check size={9} style={{ color: DS.green }} /> : <X size={9} style={{ color: DS.text4 }} />}',
I2+' </div>',
I2+' <span style={{ color: isAvailable ? DS.text : DS.text3, fontSize: 12, fontFamily: DS.mono }}>{result.domain}</span>',
I2+' </div>',
I2+' {isAvailable && result.price > 0 && (',
I2+' <span style={{ color: DS.green, fontSize: 11, fontFamily: DS.mono, fontWeight: 600 }}>{fmtVND(result.price)}</span>',
I2+' )}',
I2+' </div>',
I2+' );',
I2+' })}',
I2+' </div>',
I2+' </div>',
I2+' )}',
I2+'',
I2+' {/* Selected summary */}',
I2+' {selectedDomains.length > 0 && (',
I2+' <div className="mt-4 p-3 rounded-xl" style={{ background: `${DS.blue}08`, border: `1px solid ${DS.blue}25` }}>',
I2+' <div className="flex items-center justify-between">',
I2+' <div className="flex items-center gap-2">',
I2+' <Check size={13} style={{ color: DS.blue }} />',
I2+' <span style={{ color: DS.blue, fontSize: 12, fontFamily: DS.mono }}>Đã chọn {selectedDomains.length} domain</span>',
I2+' </div>',
I2+' <span style={{ color: DS.blue, fontSize: 13, fontFamily: DS.mono, fontWeight: 700 }}>{fmtVND(selectedDomainTotal)}</span>',
I2+' </div>',
I2+' <div className="mt-2 flex flex-wrap gap-2">',
I2+' {selectedDomains.map(d => (',
I2+' <span key={d.domain} className="flex items-center gap-1 px-2 py-1 rounded-lg text-xs" style={{ background: `${DS.blue}15`, color: DS.blue, fontFamily: DS.mono }}>',
I2+' {d.domain}',
I2+' <button onClick={() => toggleDomain(d.domain, d.price)} style={{ background: "none", border: "none", cursor: "pointer", padding: 0, color: DS.blue, display: "flex" }}>',
I2+' <X size={10} />',
I2+' </button>',
I2+' </span>',
I2+' ))}',
I2+' </div>',
I2+' </div>',
I2+' )}',
I2+' </div>',
I2+' )}',
I2+' </div>',
I2+' )}',
I2+'</div>',
].join('\r\n');

// Find the mb-6 div using string index
const marker = '<div className="mb-6">';
const markerIdx = c.indexOf(marker);
const purchaseIdx = c.indexOf(' {/* Purchase timing */}');
const sectionEnd = c.lastIndexOf('</div>', purchaseIdx);
console.log('Marker at:', markerIdx, '| Purchase at:', purchaseIdx, '| End at:', sectionEnd);

const before = c.substring(0, markerIdx);
const after = c.substring(sectionEnd + '</div>'.length);
c = before + nd + '\r\n' + after;

fs.writeFileSync(f, c);
console.log('J. Done. Lines:', c.split('\n').length);
