export type RankKey = 'iron' | 'bronze' | 'silver' | 'gold' | 'platinum' | 'ruby' | 'diamond';

export interface RankConfig {
  label: string;
  tier: number;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  glowColor: string;
  symbol: string;
  particleColor: string;
  minLevel: number;
  maxLevel: number;
  uncapped?: boolean;
  lpPerLevel: number; // LP cần để lên mỗi level trong rank này
}

export const RANKS: Record<RankKey, RankConfig> = {
  iron: {
    label: 'IRON',
    tier: 1,
    color: '#9CA3AF',
    gradientFrom: '#4B5563',
    gradientTo: '#9CA3AF',
    glowColor: 'rgba(156,163,175,0.35)',
    symbol: '⬡',
    particleColor: '#9CA3AF',
    minLevel: 1,
    maxLevel: 14,
    lpPerLevel: 100,
  },
  bronze: {
    label: 'BRONZE',
    tier: 2,
    color: '#CD7F32',
    gradientFrom: '#92400E',
    gradientTo: '#F59E0B',
    glowColor: 'rgba(205,127,50,0.55)',
    symbol: '◈',
    particleColor: '#CD7F32',
    minLevel: 15,
    maxLevel: 34,
    lpPerLevel: 350,
  },
  silver: {
    label: 'SILVER',
    tier: 3,
    color: '#CBD5E1',
    gradientFrom: '#94A3B8',
    gradientTo: '#E2E8F0',
    glowColor: 'rgba(203,213,225,0.5)',
    symbol: '◇',
    particleColor: '#CBD5E1',
    minLevel: 35,
    maxLevel: 54,
    lpPerLevel: 800,
  },
  gold: {
    label: 'GOLD',
    tier: 4,
    color: '#FFD700',
    gradientFrom: '#F59E0B',
    gradientTo: '#FDE68A',
    glowColor: 'rgba(255,215,0,0.6)',
    symbol: '★',
    particleColor: '#FFD700',
    minLevel: 55,
    maxLevel: 74,
    lpPerLevel: 2000,
  },
  platinum: {
    label: 'PLATINUM',
    tier: 5,
    color: '#14B8A6',
    gradientFrom: '#14B8A6',
    gradientTo: '#8B5CF6',
    glowColor: 'rgba(20,184,166,0.6)',
    symbol: '❋',
    particleColor: '#14B8A6',
    minLevel: 75,
    maxLevel: 94,
    lpPerLevel: 5000,
  },
  ruby: {
    label: 'RUBY',
    tier: 6,
    color: '#EF4444',
    gradientFrom: '#DC2626',
    gradientTo: '#F87171',
    glowColor: 'rgba(239,68,68,0.7)',
    symbol: '♦',
    particleColor: '#EF4444',
    minLevel: 95,
    maxLevel: 114,
    lpPerLevel: 12000,
  },
  diamond: {
    label: 'DIAMOND',
    tier: 7,
    color: '#818CF8',
    gradientFrom: '#818CF8',
    gradientTo: '#7DD3FC',
    glowColor: 'rgba(129,140,248,0.7)',
    symbol: '✦',
    particleColor: '#7DD3FC',
    minLevel: 115,
    maxLevel: 135,
    uncapped: true,
    lpPerLevel: 30000,
  },
};

export interface MissionLog {
  title: string;
  date: string;
  status: 'completed' | 'ongoing' | 'failed';
  lpReward: number;
}

export interface RankProgressEvent {
  rank: RankKey;
  level: number;
  date: string;
  note: string;
}

export interface Member {
  id: number;
  name: string;
  title: string;
  role: string;
  roleCode: string;
  team: string;
  rank: RankKey;
  level: number;
  currentXP: number;
  maxXP: number;
  lpBalance: number;    // LP hiện tại đang giữ
  lpEarned: number;     // Tổng LP đã kiếm được
  lpSpent: number;      // Tổng LP đã dùng
  img: string;
  bio: string;
  specialty: string;
  missions: number;
  achievements: string[];
  skills: Record<string, number>;
  techStack: string[];
  missionLogs: MissionLog[];
  rankHistory: RankProgressEvent[];
}

export const members: Member[] = [
  {
    id: 1,
    name: 'Kai Tanaka',
    title: 'Junior Operative',
    role: 'Frontend Dev',
    roleCode: 'BOW',
    team: 'Alpha',
    rank: 'iron',
    level: 8,
    currentXP: 45,
    maxXP: 100,
    lpBalance: 850,
    lpEarned: 1_200,
    lpSpent: 350,
    img: 'https://images.unsplash.com/photo-1769221909855-d1f62ef5aaa7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Thanh kiếm vẫn đang được rèn giũa. Tiềm năng thô đang chờ đợi ngọn lửa kinh nghiệm.',
    specialty: 'Vue.js & CSS Animations',
    missions: 12,
    achievements: ['First Deployment', 'Void Hunter', 'Code Apprentice'],
    skills: { Code: 35, Design: 20, Strategy: 15, Execution: 38, Teamwork: 30 },
    techStack: ['Vue.js', 'Tailwind CSS', 'TypeScript', 'Figma'],
    missionLogs: [
      { title: 'Landing Page Redesign', date: '2026-03-10', status: 'completed', lpReward: 200 },
      { title: 'Component Library Setup', date: '2026-02-28', status: 'completed', lpReward: 150 },
      { title: 'Dark Mode Integration', date: '2026-03-18', status: 'ongoing', lpReward: 180 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2025-11-15', note: 'Đăng ký Guild — Một thanh kiếm mới được đúc.' },
    ],
  },
  {
    id: 2,
    name: 'Mei Lin',
    title: 'Visual Artisan',
    role: 'UI/UX Designer',
    roleCode: 'STAFF',
    team: 'Sigma',
    rank: 'bronze',
    level: 24,
    currentXP: 78,
    maxXP: 100,
    lpBalance: 3_200,
    lpEarned: 8_500,
    lpSpent: 5_300,
    img: 'https://images.unsplash.com/photo-1729337531424-198f880cb6c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Một hòn than hồng rực cháy ổn định. Kỹ năng sắc bén qua từng chu kỳ thiết kế.',
    specialty: 'Design Systems & Figma',
    missions: 28,
    achievements: ['Pixel Perfect', 'Design Sage', 'Sprint Champion', 'Brand Keeper'],
    skills: { Code: 25, Design: 72, Strategy: 45, Execution: 58, Teamwork: 65 },
    techStack: ['Figma', 'Adobe XD', 'Framer', 'Protopie', 'Spline'],
    missionLogs: [
      { title: 'Dashboard Redesign v2', date: '2026-03-15', status: 'completed', lpReward: 500 },
      { title: 'Mobile App UX Audit', date: '2026-03-08', status: 'completed', lpReward: 350 },
      { title: 'Brand Identity System', date: '2026-03-20', status: 'ongoing', lpReward: 800 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2025-06-01', note: 'Đăng ký Guild — Nghệ nhân thức tỉnh.' },
      { rank: 'bronze', level: 15, date: '2025-08-12', note: 'Thăng cấp Bronze — Hoàn thành thiết kế lớn đầu tiên.' },
    ],
  },
  {
    id: 3,
    name: 'Ryo Hashimoto',
    title: 'Code Sentinel',
    role: 'Backend Dev',
    roleCode: 'DAGGER',
    team: 'Alpha',
    rank: 'silver',
    level: 43,
    currentXP: 62,
    maxXP: 100,
    lpBalance: 8_500,
    lpEarned: 22_000,
    lpSpent: 13_500,
    img: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Những con đường bạc được khắc qua vô số cơn bão debug. API phải tuân lệnh anh.',
    specialty: 'Node.js & Microservices',
    missions: 51,
    achievements: ['Centurion Coder', 'API Architect', 'Bug Slayer', 'Night Owl', 'Zero Downtime'],
    skills: { Code: 78, Design: 30, Strategy: 60, Execution: 72, Teamwork: 55 },
    techStack: ['Node.js', 'PostgreSQL', 'Redis', 'Docker', 'GraphQL'],
    missionLogs: [
      { title: 'Auth Service Overhaul', date: '2026-03-12', status: 'completed', lpReward: 1_200 },
      { title: 'Cache Layer Migration', date: '2026-03-05', status: 'completed', lpReward: 900 },
      { title: 'Payment API Integration', date: '2026-03-19', status: 'ongoing', lpReward: 1_500 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2025-01-10', note: 'Đăng ký Guild — Bước vào lò rèn.' },
      { rank: 'bronze', level: 15, date: '2025-02-28', note: 'Thăng cấp Bronze — Triển khai API đầu tiên lên production.' },
      { rank: 'silver', level: 35, date: '2025-05-20', note: 'Thăng cấp Silver — Đạt danh hiệu Centurion Coder.' },
    ],
  },
  {
    id: 4,
    name: 'Yuna Park',
    title: 'Dual-Path Operative',
    role: 'Full Stack Dev',
    roleCode: 'DUAL',
    team: 'Omega',
    rank: 'gold',
    level: 68,
    currentXP: 85,
    maxXP: 100,
    lpBalance: 15_800,
    lpEarned: 65_000,
    lpSpent: 49_200,
    img: 'https://images.unsplash.com/photo-1665615839740-f9cfcc9568f9?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Nơi mã nguồn gặp gỡ nghệ thuật — Yuna điều khiển cả hai với sự uyển chuyển tự nhiên.',
    specialty: 'React & System Architecture',
    missions: 84,
    achievements: ['Gold Standard', 'Full Stack Legend', 'Sprint MVP', 'Mentor Badge', 'Architect Seal', '1000 Commits'],
    skills: { Code: 85, Design: 70, Strategy: 75, Execution: 88, Teamwork: 80 },
    techStack: ['React', 'Next.js', 'Prisma', 'PostgreSQL', 'AWS', 'Tailwind'],
    missionLogs: [
      { title: 'E-commerce Platform v3', date: '2026-03-14', status: 'completed', lpReward: 3_000 },
      { title: 'Real-time Chat Feature', date: '2026-03-09', status: 'completed', lpReward: 2_000 },
      { title: 'SaaS Dashboard MVP', date: '2026-03-21', status: 'ongoing', lpReward: 5_000 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2024-09-05', note: 'Đăng ký Guild — Song kiếm rút khỏi bao.' },
      { rank: 'bronze', level: 15, date: '2024-10-22', note: 'Thăng cấp Bronze — Nhà vô địch triển khai Full-stack.' },
      { rank: 'silver', level: 35, date: '2025-01-14', note: 'Thăng cấp Silver — Cột mốc 1,000 commits.' },
      { rank: 'gold', level: 55, date: '2025-07-03', note: 'Thăng cấp Gold — Nhận giải thưởng Sprint MVP.' },
    ],
  },
  {
    id: 5,
    name: 'Shin Watanabe',
    title: 'Infrastructure Warden',
    role: 'DevOps Engineer',
    roleCode: 'SHIELD',
    team: 'Sigma',
    rank: 'platinum',
    level: 85,
    currentXP: 40,
    maxXP: 100,
    lpBalance: 28_500,
    lpEarned: 142_000,
    lpSpent: 113_500,
    img: 'https://images.unsplash.com/photo-1618698937393-8d7bb5f2d341?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Người thì thầm với hạ tầng. Không hệ thống nào thoát khỏi trật tự của anh. Pipeline phải tuân lệnh.',
    specialty: 'Kubernetes & CI/CD',
    missions: 103,
    achievements: ['Platinum Guard', 'Zero Incident', 'Pipeline Master', 'K8s Warden', 'Security Seal', 'SRE Elite'],
    skills: { Code: 70, Design: 25, Strategy: 88, Execution: 90, Teamwork: 72 },
    techStack: ['Kubernetes', 'Terraform', 'AWS', 'GitHub Actions', 'Prometheus', 'Grafana'],
    missionLogs: [
      { title: 'Multi-Region Deployment', date: '2026-03-11', status: 'completed', lpReward: 8_000 },
      { title: 'Security Audit & Hardening', date: '2026-03-07', status: 'completed', lpReward: 6_000 },
      { title: 'Observability Stack Setup', date: '2026-03-20', status: 'ongoing', lpReward: 10_000 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2024-03-10', note: 'Đăng ký Guild — Cai ngục vào vị trí.' },
      { rank: 'bronze', level: 15, date: '2024-05-01', note: 'Thăng cấp Bronze — Tự động hóa pipeline CI/CD đầu tiên.' },
      { rank: 'silver', level: 35, date: '2024-07-18', note: 'Thăng cấp Silver — Đạt danh hiệu Zero Incident.' },
      { rank: 'gold', level: 55, date: '2024-10-30', note: 'Thăng cấp Gold — Mở rộng cụm Kubernetes lên 50 nodes.' },
      { rank: 'platinum', level: 75, date: '2025-04-12', note: 'Thăng cấp Platinum — Nhận ấn ký Platinum Guard.' },
    ],
  },
  {
    id: 6,
    name: 'Rin Nakamura',
    title: 'Crimson Architect',
    role: 'Backend Lead',
    roleCode: 'DAGGER',
    team: 'Omega',
    rank: 'ruby',
    level: 103,
    currentXP: 60,
    maxXP: 100,
    lpBalance: 52_000,
    lpEarned: 380_000,
    lpSpent: 328_000,
    img: 'https://images.unsplash.com/photo-1725144118950-44dc92db3f09?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Sự chính xác đầy quyết đoán. Mọi hàm số là một đòn tấn công. Hệ thống phải sợ hãi những lần refactor của cô.',
    specialty: 'High-Performance Systems',
    missions: 138,
    achievements: ['Ruby Ascendant', 'Refactor Deity', 'SQL Samurai', 'API Overlord', 'Latency Slayer', 'Concurrency Master', 'Elite Hacker'],
    skills: { Code: 95, Design: 40, Strategy: 85, Execution: 96, Teamwork: 78 },
    techStack: ['Rust', 'Go', 'PostgreSQL', 'Kafka', 'gRPC', 'Kubernetes', 'ClickHouse'],
    missionLogs: [
      { title: 'Distributed Cache System', date: '2026-03-13', status: 'completed', lpReward: 20_000 },
      { title: 'Event Sourcing Migration', date: '2026-03-06', status: 'completed', lpReward: 15_000 },
      { title: '10x Performance Refactor', date: '2026-03-22', status: 'ongoing', lpReward: 25_000 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2023-08-20', note: 'Đăng ký Guild — Thanh kiếm đỏ thắm nếm máu lần đầu.' },
      { rank: 'bronze', level: 15, date: '2023-10-05', note: 'Thăng cấp Bronze — Nhận danh hiệu Bug Slayer lần đầu.' },
      { rank: 'silver', level: 35, date: '2024-01-17', note: 'Thăng cấp Silver — Xác nhận bậc thầy SQL Samurai.' },
      { rank: 'gold', level: 55, date: '2024-05-22', note: 'Thăng cấp Gold — Chiếm lấy danh hiệu API Overlord.' },
      { rank: 'platinum', level: 75, date: '2024-09-14', note: 'Thăng cấp Platinum — Đạt độ trễ dưới 1ms.' },
      { rank: 'ruby', level: 95, date: '2025-02-28', note: 'Thăng cấp Ruby — Ấn ký Ruby Ascendant được đúc trong lửa.' },
    ],
  },
  {
    id: 7,
    name: 'Akira Sato',
    title: 'Guild Master',
    role: 'Tech Lead',
    roleCode: 'MAP',
    team: 'All',
    rank: 'diamond',
    level: 118,
    currentXP: 92,
    maxXP: 100,
    lpBalance: 98_000,
    lpEarned: 820_000,
    lpSpent: 722_000,
    img: 'https://images.unsplash.com/photo-1750741268857-7e44510f867d?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Đặc vụ đỉnh cao. Một huyền thoại được khắc trên silicon và ánh sao. Guild cúi chào.',
    specialty: 'Vision & System Architecture',
    missions: 201,
    achievements: ['Diamond Ascension', 'Guild Master Seal', 'Tech Visionary', 'Legendary Architect', 'Infinite Commits', 'Team Forger', 'Lore Keeper', 'Apex Predator'],
    skills: { Code: 98, Design: 82, Strategy: 99, Execution: 97, Teamwork: 95 },
    techStack: ['Everything', 'System Design', 'Leadership', 'React', 'Go', 'Rust', 'AWS', 'GCP'],
    missionLogs: [
      { title: 'Platform Architecture Overhaul', date: '2026-03-16', status: 'completed', lpReward: 80_000 },
      { title: 'Team Scaling Strategy', date: '2026-03-10', status: 'completed', lpReward: 50_000 },
      { title: 'Next-Gen Product Vision', date: '2026-03-22', status: 'ongoing', lpReward: 100_000 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2022-04-01', note: 'Đăng ký Guild — Huyền thoại bắt đầu biên niên sử.' },
      { rank: 'bronze', level: 15, date: '2022-06-15', note: 'Thăng cấp Bronze — Bản phác thảo kiến trúc đầu tiên.' },
      { rank: 'silver', level: 35, date: '2022-09-30', note: 'Thăng cấp Silver — Tập hợp và rèn giũa đội ngũ 5 người.' },
      { rank: 'gold', level: 55, date: '2023-01-22', note: 'Thăng cấp Gold — Ra mắt Platform v1 cho 10k người dùng.' },
      { rank: 'platinum', level: 75, date: '2023-06-08', note: 'Thăng cấp Platinum — Ghi danh hiệu Lore Keeper.' },
      { rank: 'ruby', level: 95, date: '2023-12-01', note: 'Thăng cấp Ruby — Nhận ấn ký Legendary Architect.' },
      { rank: 'diamond', level: 115, date: '2024-08-18', note: 'Thăng cấp Diamond — Đăng cơ ngôi vị Guild Master.' },
    ],
  },
  {
    id: 8,
    name: 'Trần Hữu Phúc',
    title: 'Senior Operative',
    role: 'Frontend Dev',
    roleCode: 'BOW',
    team: 'Sigma',
    rank: 'bronze',
    level: 28,
    currentXP: 32,
    maxXP: 100,
    lpBalance: 4_500,
    lpEarned: 12_000,
    lpSpent: 7_500,
    img: 'https://images.unsplash.com/photo-1594085087888-9a3e2a4e2de2?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Sự chính xác trong từng pixel. Một bậc thầy của nghệ thuật dàn trang.',
    specialty: 'Tailwind CSS & React Hooks',
    missions: 34,
    achievements: ['Speed Runner', 'UI Wizard', 'Component King'],
    skills: { Code: 62, Design: 45, Strategy: 30, Execution: 55, Teamwork: 48 },
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    missionLogs: [
      { title: 'Feature Module Alpha', date: '2026-03-12', status: 'completed', lpReward: 400 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2025-05-10', note: 'Đăng ký Guild' },
      { rank: 'bronze', level: 15, date: '2025-10-02', note: 'Thăng cấp Bronze' },
    ],
  },
  {
    id: 9,
    name: 'Nguyễn Minh Thư',
    title: 'Creative Artisan',
    role: 'UI Designer',
    roleCode: 'STAFF',
    team: 'Omega',
    rank: 'silver',
    level: 48,
    currentXP: 65,
    maxXP: 100,
    lpBalance: 7_800,
    lpEarned: 25_000,
    lpSpent: 17_200,
    img: 'https://images.unsplash.com/photo-1561087548-131cd5d70dfe?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Thiết kế những giao diện đầy sức sống. Nhịp đập thẩm mỹ của guild.',
    specialty: 'Minimalist UX & Visual Systems',
    missions: 56,
    achievements: ['Golden Ratio', 'Color Master', 'Design Prophet'],
    skills: { Code: 15, Design: 88, Strategy: 50, Execution: 72, Teamwork: 68 },
    techStack: ['Figma', 'Adobe Suite', 'Spline', 'Rive'],
    missionLogs: [
      { title: 'Làm mới bộ nhận diện', date: '2026-03-18', status: 'completed', lpReward: 1_200 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2024-11-20', note: 'Gia nhập guild' },
      { rank: 'silver', level: 35, date: '2025-08-15', note: 'Thăng cấp Silver' },
    ],
  },
  {
    id: 10,
    name: 'Lê Văn Nam',
    title: 'Junior Operative',
    role: 'Backend Dev',
    roleCode: 'DAGGER',
    team: 'Alpha',
    rank: 'iron',
    level: 12,
    currentXP: 85,
    maxXP: 100,
    lpBalance: 1_200,
    lpEarned: 2_500,
    lpSpent: 1_300,
    img: 'https://images.unsplash.com/photo-1686543971025-15aa01b5f7c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Lặng lẽ, hiệu quả và sắc bén trong việc sửa lỗi. Ngôi sao đang lên trong bóng tối.',
    specialty: 'API Development & SQL Optimization',
    missions: 18,
    achievements: ['First Blood', 'Bug Hunter'],
    skills: { Code: 45, Design: 10, Strategy: 25, Execution: 40, Teamwork: 35 },
    techStack: ['Node.js', 'Express', 'PostgreSQL'],
    missionLogs: [
      { title: 'User Auth Module', date: '2026-03-21', status: 'ongoing', lpReward: 300 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2026-01-15', note: 'Bắt đầu huấn luyện' },
    ],
  },
  {
    id: 11,
    name: 'Phạm Hoàng Long',
    title: 'System Guardian',
    role: 'DevOps',
    roleCode: 'SHIELD',
    team: 'Sigma',
    rank: 'gold',
    level: 65,
    currentXP: 22,
    maxXP: 100,
    lpBalance: 12_500,
    lpEarned: 58_000,
    lpSpent: 45_500,
    img: 'https://images.unsplash.com/photo-1701463387028-3947648f1337?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Bảo vệ ranh giới hệ thống. Đảm bảo luồng dữ liệu không bao giờ bị gián đoạn.',
    specialty: 'AWS & Kubernetes',
    missions: 78,
    achievements: ['Unstoppable', 'Cloud Architect', 'Security First'],
    skills: { Code: 60, Design: 20, Strategy: 75, Execution: 82, Teamwork: 70 },
    techStack: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    missionLogs: [
      { title: 'Global Load Balancer Setup', date: '2026-03-05', status: 'completed', lpReward: 2_500 },
    ],
    rankHistory: [
      { rank: 'gold', level: 55, date: '2025-12-20', note: 'Thăng cấp Gold' },
    ],
  },
  {
    id: 12,
    name: 'Đặng Mỹ Linh',
    title: 'Strategic Overseer',
    role: 'Project Manager',
    roleCode: 'PM',
    team: 'All',
    rank: 'platinum',
    level: 88,
    currentXP: 45,
    maxXP: 100,
    lpBalance: 32_000,
    lpEarned: 135_000,
    lpSpent: 103_000,
    img: 'https://images.unsplash.com/photo-1729337531424-198f880cb6c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Điều phối các chiến dịch phức tạp với sự điềm tĩnh thiền định. Hỗn loạn là bảng vẽ của cô.',
    specialty: 'Agile Strategy & Resource Management',
    missions: 112,
    achievements: ['Master Planner', 'Efficiency Engine', 'Client Whisperer'],
    skills: { Code: 30, Design: 50, Strategy: 95, Execution: 88, Teamwork: 92 },
    techStack: ['Jira', 'Notion', 'Miro', 'ClickUp'],
    missionLogs: [
      { title: 'Q1 Vision Planning', date: '2026-03-01', status: 'completed', lpReward: 10_000 },
    ],
    rankHistory: [
      { rank: 'platinum', level: 75, date: '2025-06-30', note: 'Thăng cấp Platinum' },
    ],
  },
  {
    id: 13,
    name: 'Vũ Đình Trọng',
    title: 'Quality Sentry',
    role: 'QA Lead',
    roleCode: 'QA',
    team: 'Alpha',
    rank: 'silver',
    level: 52,
    currentXP: 15,
    maxXP: 100,
    lpBalance: 6_200,
    lpEarned: 22_000,
    lpSpent: 15_800,
    img: 'https://images.unsplash.com/photo-1766022411633-e88e3650538b?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Không lỗi nào thoát khỏi tầm mắt của lính gác. Chất lượng là định luật tối cao.',
    specialty: 'Automated Testing & Security Audits',
    missions: 64,
    achievements: ['Zero Defect', 'Test Master', 'Guardian of Quality'],
    skills: { Code: 70, Design: 20, Strategy: 60, Execution: 75, Teamwork: 65 },
    techStack: ['Cypress', 'Playwright', 'Jest', 'Postman'],
    missionLogs: [
      { title: 'Regression Suite Overhaul', date: '2026-03-15', status: 'completed', lpReward: 1_500 },
    ],
    rankHistory: [
      { rank: 'silver', level: 35, date: '2025-04-12', note: 'Thăng cấp Silver' },
    ],
  },
  {
    id: 14,
    name: 'Haru Tanaka',
    title: 'Media Artisan',
    role: 'Media Manager',
    roleCode: 'MKT',
    team: 'All',
    rank: 'ruby',
    level: 72,
    currentXP: 88,
    maxXP: 100,
    lpBalance: 45_000,
    lpEarned: 175_000,
    lpSpent: 130_000,
    img: 'https://images.unsplash.com/photo-1612192279155-f7fab0a4f377?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Kiến trúc sư của hình ảnh và âm thanh. Mỗi khung hình là một tuyên bố nghệ thuật. Đội ngũ media dưới sự dẫn dắt của anh.',
    specialty: 'Media Production & Brand Identity',
    missions: 68,
    achievements: ['Visual Master', 'Brand Architect', 'Media Maven', 'Story Teller'],
    skills: { Code: 30, Design: 88, Strategy: 75, Execution: 82, Teamwork: 90 },
    techStack: ['Adobe Premiere', 'After Effects', 'Figma', 'DaVinci Resolve', 'Blender'],
    missionLogs: [
      { title: 'FashionX Brand Identity', date: '2026-03-15', status: 'completed', lpReward: 6_000 },
      { title: 'CafeHouse Food Photography', date: '2026-03-10', status: 'completed', lpReward: 4_500 },
      { title: 'LOOP Brand Guidelines v2', date: '2026-03-22', status: 'ongoing', lpReward: 8_000 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2025-03-10', note: 'Đăng ký Guild — Media artisan gia nhập.' },
      { rank: 'bronze', level: 15, date: '2025-05-20', note: 'Thăng cấp Bronze — Hoàn thành FashionX brand.' },
      { rank: 'silver', level: 35, date: '2025-09-15', note: 'Thăng cấp Silver — Visual Master achievement.' },
      { rank: 'gold', level: 55, date: '2025-12-01', note: 'Thăng cấp Gold — Brand Architect achievement.' },
      { rank: 'ruby', level: 95, date: '2026-03-10', note: 'Thăng cấp Ruby — Media Maven achievement.' },
    ],
  },
  {
    id: 15,
    name: 'Lý Gia Hưng',
    title: 'Data Oracle',
    role: 'Data Scientist',
    roleCode: 'DATA',
    team: 'Sigma',
    rank: 'platinum',
    level: 82,
    currentXP: 38,
    maxXP: 100,
    lpBalance: 24_000,
    lpEarned: 110_000,
    lpSpent: 86_000,
    img: 'https://images.unsplash.com/photo-1618698937393-8d7bb5f2d341?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Nhìn thấy các mô hình nơi người khác chỉ thấy sự nhiễu loạn. Nhà tiên tri của guild.',
    specialty: 'Predictive Analytics & AI Models',
    missions: 105,
    achievements: ['Data Prophet', 'Pattern Seeker', 'AI Pioneer'],
    skills: { Code: 82, Design: 30, Strategy: 88, Execution: 90, Teamwork: 75 },
    techStack: ['Python', 'TensorFlow', 'PyTorch', 'Pandas'],
    missionLogs: [
      { title: 'Market Trend Analysis', date: '2026-03-08', status: 'completed', lpReward: 8_000 },
    ],
    rankHistory: [
      { rank: 'platinum', level: 75, date: '2025-11-05', note: 'Thăng cấp Platinum' },
    ],
  },
  {
    id: 17,
    name: 'Dương Bảo Ngọc',
    title: 'Vocal Vanguard',
    role: 'Marketing Lead',
    roleCode: 'MKT',
    team: 'Omega',
    rank: 'gold',
    level: 62,
    currentXP: 55,
    maxXP: 100,
    lpBalance: 11_200,
    lpEarned: 45_000,
    lpSpent: 33_800,
    img: 'https://images.unsplash.com/photo-1665615839740-f9cfcc9568f9?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Khuếch đại tiếng vang của guild khắp cõi hư vô kỹ thuật số.',
    specialty: 'Growth Hacking & Brand Narrative',
    missions: 82,
    achievements: ['Market Dominator', 'Narrative Weaver', 'Viral Architect'],
    skills: { Code: 20, Design: 65, Strategy: 90, Execution: 82, Teamwork: 88 },
    techStack: ['Google Ads', 'Meta Ads', 'SEO', 'Analytics'],
    missionLogs: [
      { title: 'Campaign Season 4 Launch', date: '2026-03-12', status: 'completed', lpReward: 5_000 },
    ],
    rankHistory: [
      { rank: 'gold', level: 55, date: '2025-10-30', note: 'Thăng cấp Gold' },
    ],
  },
  {
    id: 18,
    name: 'Bùi Tiến Dũng',
    title: 'Mobile Specialist',
    role: 'Mobile Developer',
    roleCode: 'BOW',
    team: 'Alpha',
    rank: 'bronze',
    level: 32,
    currentXP: 42,
    maxXP: 100,
    lpBalance: 3_800,
    lpEarned: 15_000,
    lpSpent: 11_200,
    img: 'https://images.unsplash.com/photo-1594085087888-9a3e2a4e2de2?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Xây dựng những trải nghiệm bản địa nằm gọn trong lòng bàn tay bạn.',
    specialty: 'React Native & iOS Development',
    missions: 42,
    achievements: ['App Master', 'Native Wizard'],
    skills: { Code: 68, Design: 50, Strategy: 35, Execution: 62, Teamwork: 55 },
    techStack: ['React Native', 'Swift', 'Kotlin', 'Expo'],
    missionLogs: [
      { title: 'Mobile Client v2.1', date: '2026-03-19', status: 'completed', lpReward: 800 },
    ],
    rankHistory: [
      { rank: 'bronze', level: 15, date: '2025-07-22', note: 'Thăng cấp Bronze' },
    ],
  },
  {
    id: 19,
    name: 'Hồ Diệu Thảo',
    title: 'Culture Guardian',
    role: 'HR Specialist',
    roleCode: 'HR',
    team: 'All',
    rank: 'silver',
    level: 42,
    currentXP: 28,
    maxXP: 100,
    lpBalance: 5_500,
    lpEarned: 18_000,
    lpSpent: 12_500,
    img: 'https://images.unsplash.com/photo-1729337531424-198f880cb6c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Nuôi dưỡng yếu tố con người trong guild silicon.',
    specialty: 'Talent Acquisition & Guild Culture',
    missions: 48,
    achievements: ['Culture Hero', 'Talent Scout'],
    skills: { Code: 10, Design: 35, Strategy: 65, Execution: 60, Teamwork: 95 },
    techStack: ['LinkedIn', 'Notion', 'Slack'],
    missionLogs: [
      { title: 'Hiring Sprint Q1', date: '2026-03-05', status: 'completed', lpReward: 2_000 },
    ],
    rankHistory: [
      { rank: 'silver', level: 35, date: '2025-12-15', note: 'Thăng cấp Silver' },
    ],
  },
  {
    id: 20,
    name: 'Trương Công Định',
    title: 'Product Visionary',
    role: 'Product Owner',
    roleCode: 'PO',
    team: 'Sigma',
    rank: 'platinum',
    level: 92,
    currentXP: 68,
    maxXP: 100,
    lpBalance: 35_000,
    lpEarned: 150_000,
    lpSpent: 115_000,
    img: 'https://images.unsplash.com/photo-1766022411633-e88e3650538b?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Xác định con đường phía trước. Kim chỉ nam cho sự tiến hóa sản phẩm của guild.',
    specialty: 'Product Lifecycle & Market Strategy',
    missions: 124,
    achievements: ['Vision Master', 'Product Sensei', 'Market Guru'],
    skills: { Code: 40, Design: 60, Strategy: 98, Execution: 85, Teamwork: 88 },
    techStack: ['Jira', 'Amplitude', 'Hotjar', 'Mixpanel'],
    missionLogs: [
      { title: 'Roadmap 2026 Strategy', date: '2026-03-10', status: 'completed', lpReward: 12_000 },
    ],
    rankHistory: [
      { rank: 'platinum', level: 75, date: '2025-05-15', note: 'Thăng cấp Platinum' },
    ],
  },
  {
    id: 21,
    name: 'Đỗ Quyên',
    title: 'Visual Master',
    role: 'UI/UX Designer',
    roleCode: 'STAFF',
    team: 'Omega',
    rank: 'ruby',
    level: 98,
    currentXP: 12,
    maxXP: 100,
    lpBalance: 48_000,
    lpEarned: 320_000,
    lpSpent: 272_000,
    img: 'https://images.unsplash.com/photo-1561087548-131cd5d70dfe?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Vượt lên trên những giao diện. Tạo ra những trải nghiệm số chạm đến tâm hồn.',
    specialty: 'Immersive UX & Design Psychology',
    missions: 142,
    achievements: ['Design Deity', 'Psychology Expert', 'Experience Master'],
    skills: { Code: 25, Design: 98, Strategy: 85, Execution: 92, Teamwork: 80 },
    techStack: ['Figma', 'Blender', 'After Effects', 'Protopie'],
    missionLogs: [
      { title: 'New Product Concept Design', date: '2026-03-15', status: 'completed', lpReward: 25_000 },
    ],
    rankHistory: [
      { rank: 'ruby', level: 95, date: '2025-11-20', note: 'Thăng cấp Ruby' },
    ],
  },
  {
    id: 22,
    name: 'Phan Anh Tuấn',
    title: 'Digital Sentinel',
    role: 'Security Engineer',
    roleCode: 'SHIELD',
    team: 'Sigma',
    rank: 'ruby',
    level: 105,
    currentXP: 45,
    maxXP: 100,
    lpBalance: 55_000,
    lpEarned: 400_000,
    lpSpent: 345_000,
    img: 'https://images.unsplash.com/photo-1701463387028-3947648f1337?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Lá chắn tối thượng. Bảo vệ tài sản số của guild với sự cảnh giác không lay chuyển.',
    specialty: 'Cybersecurity & Ethical Hacking',
    missions: 156,
    achievements: ['The Wall', 'Breach Slayer', 'Security Legend'],
    skills: { Code: 85, Design: 10, Strategy: 92, Execution: 96, Teamwork: 70 },
    techStack: ['Kali Linux', 'Metasploit', 'Wireshark', 'Burp Suite'],
    missionLogs: [
      { title: 'Guild Security Hardening', date: '2026-03-22', status: 'ongoing', lpReward: 30_000 },
    ],
    rankHistory: [
      { rank: 'ruby', level: 95, date: '2025-08-10', note: 'Thăng cấp Ruby' },
    ],
  },
  {
    id: 23,
    name: 'Võ Minh Tuấn',
    title: 'Grand Architect',
    role: 'Solution Architect',
    roleCode: 'MAP',
    team: 'All',
    rank: 'diamond',
    level: 122,
    currentXP: 15,
    maxXP: 100,
    lpBalance: 110_000,
    lpEarned: 950_000,
    lpSpent: 840_000,
    img: 'https://images.unsplash.com/photo-1750741268857-7e44510f867d?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Phác thảo bản thiết kế của tương lai. Kiến trúc sư của những hệ thống phức tạp nhất.',
    specialty: 'Distributed Systems & Enterprise Architecture',
    missions: 215,
    achievements: ['Diamond Architect', 'System Legend', 'Infinite Scale'],
    skills: { Code: 95, Design: 75, Strategy: 100, Execution: 98, Teamwork: 90 },
    techStack: ['Microservices', 'Event Sourcing', 'Cloud Native', 'Kubernetes'],
    missionLogs: [
      { title: 'Enterprise Core Migration', date: '2026-03-18', status: 'completed', lpReward: 100_000 },
    ],
    rankHistory: [
      { rank: 'diamond', level: 115, date: '2025-10-15', note: 'Thăng cấp Diamond' },
    ],
  },
  {
    id: 24,
    name: 'Mai Phương Linh',
    title: 'Messenger',
    role: 'Content Strategist',
    roleCode: 'MKT',
    team: 'Omega',
    rank: 'iron',
    level: 5,
    currentXP: 62,
    maxXP: 100,
    lpBalance: 650,
    lpEarned: 1_500,
    lpSpent: 850,
    img: 'https://images.unsplash.com/photo-1729337531424-198f880cb6c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Xây dựng những thông điệp xuyên qua sự nhiễu loạn. Một giọng nói đang tìm kiếm âm điệu.',
    specialty: 'Copywriting & Content Marketing',
    missions: 8,
    achievements: ['First Story', 'Word Smith'],
    skills: { Code: 5, Design: 40, Strategy: 35, Execution: 30, Teamwork: 65 },
    techStack: ['Notion', 'Grammarly', 'Canva'],
    missionLogs: [
      { title: 'Newsletter Launch', date: '2026-03-21', status: 'ongoing', lpReward: 200 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2026-02-10', note: 'Đăng ký' },
    ],
  },
  {
    id: 25,
    name: 'Cao Hữu Việt',
    title: 'Initiate',
    role: 'Junior Backend',
    roleCode: 'DAGGER',
    team: 'Alpha',
    rank: 'iron',
    level: 14,
    currentXP: 95,
    maxXP: 100,
    lpBalance: 1_500,
    lpEarned: 3_200,
    lpSpent: 1_700,
    img: 'https://images.unsplash.com/photo-1686543971025-15aa01b5f7c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Mài giũa thanh kiếm Backend. Hiệu quả là mục tiêu cuối cùng.',
    specialty: 'Node.js Basics & Database Queries',
    missions: 15,
    achievements: ['Query Master', 'First API'],
    skills: { Code: 52, Design: 5, Strategy: 15, Execution: 45, Teamwork: 40 },
    techStack: ['Node.js', 'MySQL', 'JavaScript'],
    missionLogs: [
      { title: 'Bug Fix Marathon', date: '2026-03-20', status: 'completed', lpReward: 400 },
    ],
    rankHistory: [
      { rank: 'iron', level: 1, date: '2026-01-05', note: 'Trạng thái Initiate' },
    ],
  },
  {
    id: 26,
    name: 'Đoàn Minh Quân',
    title: 'Elite Operative',
    role: 'Senior Frontend',
    roleCode: 'BOW',
    team: 'Sigma',
    rank: 'platinum',
    level: 94,
    currentXP: 92,
    maxXP: 100,
    lpBalance: 42_000,
    lpEarned: 210_000,
    lpSpent: 168_000,
    img: 'https://images.unsplash.com/photo-1594085087888-9a3e2a4e2de2?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Làm chủ nghệ thuật tương tác. Mỗi khung hình là một sự lựa chọn có chủ đích.',
    specialty: 'Animation Systems & State Management',
    missions: 132,
    achievements: ['Motion Deity', 'State Master', 'UI Guru'],
    skills: { Code: 94, Design: 70, Strategy: 75, Execution: 92, Teamwork: 85 },
    techStack: ['React', 'Zustand', 'Framer Motion', 'Three.js'],
    missionLogs: [
      { title: '3D Portfolio Integration', date: '2026-03-12', status: 'completed', lpReward: 15_000 },
    ],
    rankHistory: [
      { rank: 'platinum', level: 75, date: '2025-04-10', note: 'Thăng cấp Platinum' },
    ],
  },
  {
    id: 26,
    name: 'Tạ Minh Tâm',
    title: 'Void Weaver',
    role: 'Blockchain Developer',
    roleCode: 'DUAL',
    team: 'Omega',
    rank: 'ruby',
    level: 112,
    currentXP: 82,
    maxXP: 100,
    lpBalance: 68_000,
    lpEarned: 480_000,
    lpSpent: 412_000,
    img: 'https://images.unsplash.com/photo-1547137289-636000d1ec10?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Dệt nên niềm tin vào hư vô. Bậc thầy của sổ cái bất biến.',
    specialty: 'Smart Contracts & DeFi Architecture',
    missions: 164,
    achievements: ['Ledger Master', 'Contract Guru', 'Void Weaver'],
    skills: { Code: 96, Design: 35, Strategy: 90, Execution: 95, Teamwork: 75 },
    techStack: ['Solidity', 'Rust', 'Web3.js', 'Ethereum'],
    missionLogs: [
      { title: 'Smart Contract Audit', date: '2026-03-19', status: 'completed', lpReward: 35_000 },
    ],
    rankHistory: [
      { rank: 'ruby', level: 95, date: '2025-07-15', note: 'Thăng cấp Ruby' },
    ],
  },
  {
    id: 27,
    name: 'Đinh Tiến Đạt',
    title: 'Talent Scout',
    role: 'Tech Recruiter',
    roleCode: 'HR',
    team: 'All',
    rank: 'bronze',
    level: 22,
    currentXP: 58,
    maxXP: 100,
    lpBalance: 2_800,
    lpEarned: 10_000,
    lpSpent: 7_200,
    img: 'https://images.unsplash.com/photo-1686543971025-15aa01b5f7c7?auto=format&fit=crop&w=400&h=560&crop=faces',
    bio: 'Xác định những huyền thoại tiếp theo trước khi họ tự nhận ra điều đó.',
    specialty: 'Sourcing & Technical Assessment',
    missions: 28,
    achievements: ['Eagle Eye', 'Connector'],
    skills: { Code: 35, Design: 15, Strategy: 55, Execution: 50, Teamwork: 88 },
    techStack: ['LinkedIn Recruiter', 'Greenhouse', 'Notion'],
    missionLogs: [
      { title: 'Tech Talent Pipeline Build', date: '2026-03-22', status: 'ongoing', lpReward: 1_200 },
    ],
    rankHistory: [
      { rank: 'bronze', level: 15, date: '2025-11-20', note: 'Thăng cấp Bronze' },
    ],
  },
];
