import { handleError, ok } from "@/lib/api/response";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/auth/permissions";
import { createAuditLog } from "@/lib/auth/audit";
import { recordPayment } from "@/lib/pricing/order-lifecycle";
import { autoGenerateInvoice, notifyInvoiceAutoGenerated } from "@/lib/services/commerce/invoice.service";
import { notify } from "@/lib/services/notification/admin-notification.service";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await requirePermission("orders", "read");
    const { id } = await params;

    const payments = await prisma.payment.findMany({
      where: { orderId: id },
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json({ data: payments });
  } catch (error) {
    return handleError(error);
  }
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await requirePermission("orders", "update");
    const { id } = await params;
    const { amount, method, note } = await req.json();

    if (!amount || typeof amount !== "number") {
      return NextResponse.json(
        { error: "amount is required and must be a number" },
        { status: 400 }
      );
    }

    const result = await recordPayment(id, amount, method, note, session.userId);

    if (!result.success) {
      return NextResponse.json({ error: result.error }, { status: 400 });
    }

    // ── P1-7 FIX: fetch order for urgency logic ─────────────────────────────
    const order = await prisma.order.findUnique({
      where: { id },
      select: { finalPrice: true, totalAmount: true, orderNumber: true },
    });
    const totalExpected = order?.finalPrice ?? order?.totalAmount ?? 0;

    // ── Audit log ─────────────────────────────────────────────────────────
    await createAuditLog({
      userId: session.userId,
      action: "create",
      resource: "orders",
      resourceId: id,
      newValues: { amount, method, note },
    });

    // ── Admin notification via template ────────────────────────────────────
    void notify("payment_received", {
      amount: new Intl.NumberFormat("vi-VN").format(amount),
      orderNumber: order?.orderNumber ?? id,
      method: method ?? "",
    }, {
      link: `/admin/orders`,
      amountVnd: amount,
    });

    // ── P1-2: Auto-generate Invoice ───────────────────────────────────────
    // Fire-and-forget, non-blocking — runs after payment commits
    void autoGenerateInvoice({
      orderId: id,
      paymentAmount: amount,
      paymentMethod: method ?? "other",
      createdBy: session.userId,
    }).then((inv) => {
      if (inv) {
        void notifyInvoiceAutoGenerated(inv.invoiceNumber, id, amount);
      }
    }).catch(() => {/* silent — non-critical */ });

    // ── P1-3: Send customer payment confirmation email ──────────────────────
    // Fire-and-forget
    void prisma.order.findUnique({
      where: { id },
      select: { orderNumber: true, customerName: true, customerEmail: true },
    }).then(async (o) => {
      if (!o?.customerEmail) return;
      try {
        const { sendPaymentConfirmationEmail } = await import("@/lib/email/sender");
        await sendPaymentConfirmationEmail({
          orderNumber: o.orderNumber ?? id,
          customerName: o.customerName ?? "",
          customerEmail: o.customerEmail ?? "",
          totalAmount: amount,
          paidAmount: amount,
          paymentMethod: method ?? "other",
        });
      } catch {
        // silent — email non-critical
      }
    }).catch(() => {/* silent */ });

    return ok({ success: true });
  } catch (error) {
    return handleError(error);
  }
}
