/**
 * Sitemap — LOOP Solutions
 * Locale-aware sitemap for VI + EN (Phase 0).
 * Phase 1: add JA + KO
 * Phase 2: add ZH
 */

import type { MetadataRoute } from "next";
import { routing } from "@/i18n/routing";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _Locale = (typeof routing.locales)[number];

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://loop.vn";

export const revalidate = 3600;

/**
 * Static routes shared across all locales.
 */
const staticRoutes = [
  { path: "", priority: 1.0, changeFrequency: "weekly" as const },
  { path: "services", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "portfolio", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "pricing", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "about", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "team", priority: 0.6, changeFrequency: "monthly" as const },
  { path: "blog", priority: 0.6, changeFrequency: "weekly" as const },
  { path: "contact", priority: 0.5, changeFrequency: "monthly" as const },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const entries: MetadataRoute.Sitemap = [];

  // ─── Static pages (all locales) ─────────────────────────────────────────────
  for (const locale of routing.locales as unknown as string[]) {
    for (const route of staticRoutes) {
      entries.push({
        url: `${baseUrl}/${locale}${route.path ? `/${route.path}` : ""}`,
        lastModified: new Date(),
        changeFrequency: route.changeFrequency,
        priority: route.priority,
        // hreflang variants are automatically generated by Next.js
        // via generate hreflang links in page metadata
      });
    }
  }

  return entries;
}
